# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170522_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('date_joined',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
