# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 19:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaflets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('leaf_type', models.TextField(default='text', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('leaflet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='leaflets.Leaflet')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
