# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
        ('leaflets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaflet',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaflets', to='sections.Section'),
        ),
    ]
