# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='notebooks.Notebook')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
