# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaflets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('section_id', models.BigIntegerField()),
                ('leaflet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaflets.Leaflet')),
            ],
        ),
    ]
