# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='ffffff', max_length=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_when', models.DateTimeField(auto_now_add=True)),
                ('location', models.PositiveIntegerField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
